# Generated by Django 5.1.2 on 2024-10-25 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('users', models.ManyToManyField(blank=True, related_name='teams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeamUserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('project_manager', 'Project Manager'), ('tester', 'Tester'), ('frontend_developer', 'Frontend Developer'), ('backend_developer', 'Backend Developer'), ('fullstack_developer', 'Fullstack Developer'), ('devops', 'DevOps Engineer'), ('data_scientist', 'Data Scientist'), ('qa_engineer', 'QA Engineer'), ('designer', 'Designer'), ('ui_ux_designer', 'UI/UX Designer'), ('scrum_master', 'Scrum Master'), ('business_analyst', 'Business Analyst'), ('product_owner', 'Product Owner'), ('technical_lead', 'Technical Lead')], max_length=20)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_app.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('team', 'user')},
            },
        ),
        migrations.AddField(
            model_name='team',
            name='team_users',
            field=models.ManyToManyField(blank=True, related_name='team_roles', through='erp_app.TeamUserRole', to=settings.AUTH_USER_MODEL),
        ),
    ]
