# Generated by Django 5.1.2 on 2024-10-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0002_project_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='team_users',
        ),
        migrations.RemoveField(
            model_name='team',
            name='users',
        ),
        migrations.AddField(
            model_name='team',
            name='identifier',
            field=models.CharField(default='', max_length=6, unique=True),
        ),
    ]
