# Generated by Django 5.1.2 on 2024-10-23 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0004_user_last_login_alter_user_email_alter_user_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
